### ISSUE TITLE
Build failure on macOS

### ISSUE THREAD

**Issue by maoe** [asayers/tailsrv#1]
It fails to build on macOS Monterey 12.1:

```
   Compiling tailsrv v0.4.0
error[E0061]: this function takes 6 arguments but 4 arguments were supplied
   --> /Users/maoe/.cargo/registry/src/github.com-1ecc6299db9ec823/tailsrv-0.4.0/src/main.rs:143:13
    |
143 |             nix::sys::sendfile::sendfile(sock.as_raw_fd(), fd, Some(&mut offset), cnt)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ----------------  --  -----------------  --- supplied 4 arguments
    |             |
    |             expected 6 arguments
    |
note: function defined here
   --> /Users/maoe/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.23.1/src/sys/sendfile.rs:209:16
    |
209 |         pub fn sendfile(
    |                ^^^^^^^^

error[E0599]: no method named `map_err` found for tuple `(std::result::Result<(), Errno>, i64)` in the current scope
   --> /Users/maoe/.cargo/registry/src/github.com-1ecc6299db9ec823/tailsrv-0.4.0/src/main.rs:144:18
    |
144 |                 .map_err(std::io::Error::from)
    |                  ^^^^^^^ method not found in `(std::result::Result<(), Errno>, i64)`

Some errors have detailed explanations: E0061, E0599.
For more information about an error, try `rustc --explain E0061`.
error: failed to compile `tailsrv v0.4.0`, intermediate artifacts can be found at `/var/folders/3t/ycv0ctpn4qb5k7djxy72k4dm0000gn/T/cargo-installX2eQ5X`

Caused by:
  could not compile `tailsrv` due to 2 previous errors
```

**Comment by asayers** [comment]
Yes, I'm afraid tailsrv is Linux-only, as it uses sendfile and inotify.
